
services:
  - type: web
    name: farm-stack-backend
    buildCommand: /opt/render/project/src/.venv/bin/python3.10 -m pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 4
    env:
      - key: PYTHONUNBUFFERED
        value: "1"