

services:
  - type: web
    name: farm-stack-backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 443 --workers 4
    env:
      - key: PYTHONUNBUFFERED
        value: "1"
    publishDirectory: .
